#!/usr/bin/env bash
# Builds the single-file browser artifact from the two source files.
# The logic file is pasted in unchanged (only the word "export" is removed),
# so the code that was tested is exactly the code that runs.
set -euo pipefail
cd "$(dirname "$0")"
OUT=dist/edusphere-prototype.jsx
mkdir -p dist
{
  echo '// EduSphere prototype (Phase 0). Generated by build.sh from src/logic.mjs + src/curriculum.mjs + src/ui.jsx. Edit those files, not this one.'
  echo 'import React, { useState, useEffect, useMemo, useRef } from "react";'
  echo
  sed 's/^export default /export default /; s/^export //' src/logic.mjs
  echo
  sed 's/^export //' src/curriculum.mjs
  # The build writes its own timestamp into the page, so a cached copy can be told from a fresh one.
  sed "s/__BUILD_STAMP__/$(date -u '+%Y-%m-%d %H:%M UTC')/" src/ui.jsx
} > "$OUT"
echo "built $OUT ($(wc -l < "$OUT") lines)"
# The standalone page for GitHub Pages and every other plain web host.
node tools/build-site.mjs
